# Recording parameters
videoFolder: "D:/cam/campy/videos/test_2cams_4"
videoFilename: "vid.mp4"
frameRate: null
recTimeInSec: 14400 # total recording time, across all files.
# recTimeInSec: 14400 # total recording time, across all files.

# Trial-based recording
trialStructure: True
trialITI: 100
triggerMode: "On"

# Camera settings
# TriggerMode: "On"

# Camera parameters
cameraMake: "flir"
numCams: 2
cameraSelection: [0, 1]
cameraSettings: ""
cameraSettingsDir: "C:/LT/code/campy/campy/cameras/flir/settings"
cameraNames: ['Camera1', 'Camera2']

# Compression parameters
ffmpegLogLevel: "quiet"
gpuID: 0
gpuMake: "nvidia"
# pixelFormatInput: "bgr8" # 'bayer_bggr8' 'rgb24' BLACKFLY
# pixelFormatInput: "bayer_bggr8" # 'bayer_bggr8' 'rgb24' FLEA
pixelFormatInput: "bayer_rggb8" # 'bayer_bggr8' 'rgb24' FLEA
pixelFormatOutput: "rgb0"
codec: "h264"
quality: "21"

# Display parameters
chunkLengthInSec: 30
displayFrameRate: 10
displayDownsample: 2

# Other parameters
ffmpegPath: [] #["/home/usr/Documents/ffmpeg/ffmpeg"]
frameWidth: null
# frameHeight: [480, 480]
# frameWidth: [352, 352]
frameHeight: null
# frameWidth: 1152
# frameHeight: 1024